[build]
  builder = "nixpacks"

[deploy]
  restartPolicyType = "always"
  healthcheckPath = "/actuator/health"
  healthcheckTimeout = 90

[env]
  JAVA_VERSION = "17"
  MAVEN_OPTS = "-Xmx1536m -Dmaven.compile.fork=true"
  NIXPACKS_JDK_VERSION = "17"