[build]
  builder = "nixpacks"

[deploy]
  restartPolicyType = "always"

[env]
  JAVA_VERSION = "17"
  MAVEN_OPTS = "-Xmx1024m -Dmaven.compile.fork=true"
  NIXPACKS_JDK_VERSION = "17"
  JAVA_OPTS = "-Xms256m -Xmx512m"